openapi: "3.0.0"
components:
  schemas:
    Field:
      allOf:
        - type: object
          description: table Field
          properties:
            id:
              readOnly: true
              type: string
              description: id of table
              example: F1
            name:
              readOnly: false
              type: string
              description: name of field
              example:
            type_id:
              $ref: '#/components/schemas/Type'
            gentype_id:
              $ref: '#/components/schemas/GenType'
            option_id:
              $ref: '#/components/schemas/Option'
    Type:
      allOf:
        - type: object
          description: table Type
          properties:
            id:
              readOnly: true
              type: string
              description: id of table
            type:
              readOnly: false
              type: string
              description: name of field
            description:
              readOnly: false
              type: string
              description: type in SQL
    GenType:
      allOf:
        - type: object
          description: table GenType
          properties:
            id:
              readOnly: true
              type: string
              description: id of table
            type:
              readOnly: false
              type: string
              description: type for generate
            description:
              readOnly: false
              type: string
              description: description for generate type
            category_id:
              $ref: '#/components/schemas/Category'
    Category:
      allOf:
        - type: object
          description: table Category
          properties:
            id:
              readOnly: true
              type: string
              description: id of table
            type:
              readOnly: false
              type: string
              description: name of category
            description:
              readOnly: false
              type: string
              description: description for generate type
    Data:
      allOf:
        - type: object
          description: table Data
          properties:
            id:
              readOnly: true
              type: string
              description: id of table
            value:
              readOnly: false
              type: string
              description: value of data
            gentype_id:
              $ref: '#/components/schemas/GenType'
    Option:
      allOf:
        - type: object
          description: table Option
          properties:
            id:
              readOnly: true
              type: string
              description: id of table
            blank:
              readOnly: false
              type: integer
              description: blank percent


