openapi: "3.0.0"
info:
  title: Mockez API
  description: Website MOCKEZ generates data for system testing.
  version: 0.0.1
paths:
  /users:
    get:
      summary: Returns a list of users.
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200': # status code
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
components:
  schemas:
    Field:
      type: object
      required:
        - id
        - name
        - type
        - gentype
        - option
      description: FIELD table
      properties:
        id:
          readOnly: true
          type: string
          description: id of table
        name:
          type: string
          description: name of field
        type:
          $ref: '#/components/schemas/Type'
        gentype:
          $ref: '#/components/schemas/GenType'
        option:
          $ref: '#/components/schemas/Option'
    Type:
      type: object
      required:
        - id
        - type
        - description
      description: TYPE table
      properties:
        id:
          readOnly: true
          type: string
          description: id of table
        type:
          type: string
          description: name of field
        description:
          type: string
          description: type in SQL
    GenType:
      type: object
      required:
        - id
        - type
        - description
        - category
      description: GENTYPE table
      properties:
        id:
          readOnly: true
          type: string
          description: id of table
        type:
          type: string
          description: type for generate
        description:
          type: string
          description: description for generate type
        category:
          $ref: '#/components/schemas/Category'
        data:
          type: array
          items:
            $ref: '#/components/schemas/Data'
    Category:
      type: object
      required:
        - id
        - type
        - description
      description: CATEGORY table
      properties:
        id:
          readOnly: true
          type: string
          description: id of table
        type:
          type: string
          description: name of category
        description:
          type: string
          description: description for generate type
        gentypes:
          type: array
          items:
            $ref: '#/components/schemas/GenType'
    Data:
      type: object
      required:
        - id
        - value
        - gentype
      description: DATA table
      properties:
        id:
          readOnly: true
          type: string
          description: id of table
        value:
          type: string
          description: value of data
        gentype:
          $ref: '#/components/schemas/GenType'
    Option:
      type: object
      required:
        - id
        - blank
      description: OPTION table
      properties:
        id:
          readOnly: true
          type: string
          description: id of table
        blank:
          default: 0
          type: integer
          description: blank percent


