openapi: "3.0.3"
info:
  title: Mockez API
  description: Website MOCKEZ generates source for system testing.
  version: 1.0.0
paths:
  /sql-type:
    get:
      operationId: getSQLTypes
      tags:
        - SQLType
      description: Get all SQLType from source
      responses:
        200:
          description: The query is successful
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SQLType'
        400:
          $ref: '#/components/responses/BadRequest'
        401:
          $ref: '#/components/responses/AuthenticationError'
        403:
          $ref: '#/components/responses/Unauthorized'
        404:
          $ref: '#/components/responses/NotFound'
        500:
          $ref: '#/components/responses/ServerError'
  /category:
    get:
      operationId: getCategories
      tags:
        - Category
      description: Get all category from source
      responses:
        200:
          description: The query is successful
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'
        400:
          $ref: '#/components/responses/BadRequest'
        401:
          $ref: '#/components/responses/AuthenticationError'
        403:
          $ref: '#/components/responses/Unauthorized'
        404:
          $ref: '#/components/responses/NotFound'
        500:
          $ref: '#/components/responses/ServerError'
  /category/{id}:
    parameters:
      - in: path
        name: id
        required: true
        description: The Category ID
        schema:
          type: string
    get:
      operationId: getCategory
      tags:
        - Category
      description: Return a category
      responses:
        200:
          description: The query is successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
        400:
          $ref: '#/components/responses/BadRequest'
        401:
          $ref: '#/components/responses/AuthenticationError'
        403:
          $ref: '#/components/responses/Unauthorized'
        404:
          $ref: '#/components/responses/NotFound'
        500:
          $ref: '#/components/responses/ServerError'
  /generate-type/{id}:
    parameters:
      - in: path
        name: id
        required: true
        description: The GenerateType ID
        schema:
          type: string
    get:
      operationId: getGenerateType
      tags:
        - GenerateType
      description: Return a generatetype
      responses:
        200:
          description: The query is successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenerateType'
        400:
          $ref: '#/components/responses/BadRequest'
        401:
          $ref: '#/components/responses/AuthenticationError'
        403:
          $ref: '#/components/responses/Unauthorized'
        404:
          $ref: '#/components/responses/NotFound'
        500:
          $ref: '#/components/responses/ServerError'
  /generate-type/{sqlTypeId}:
    parameters:
      - in: path
        name: sqlTypeId
        required: true
        description: The sqlTypeId
        schema:
          type: string
    get:
      operationId: getGenerateTypeBySQLTypeId
      tags:
        - GenerateType
      description: Return a generateType by SQLTypeId
      responses:
        200:
          description: The query is successful
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GenerateType'
        400:
          $ref: '#/components/responses/BadRequest'
        401:
          $ref: '#/components/responses/AuthenticationError'
        403:
          $ref: '#/components/responses/Unauthorized'
        404:
          $ref: '#/components/responses/NotFound'
        500:
          $ref: '#/components/responses/ServerError'
  /generate-type:
    get:
      operationId: getGenerateTypes
      tags:
        - GenerateType
      description: Get all GenerateType from source
      responses:
        200:
          description: The query is successful
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GenerateType'
        400:
          $ref: '#/components/responses/BadRequest'
        401:
          $ref: '#/components/responses/AuthenticationError'
        403:
          $ref: '#/components/responses/Unauthorized'
        404:
          $ref: '#/components/responses/NotFound'
        500:
          $ref: '#/components/responses/ServerError'
  /generate:
    post:
      operationId: generate
      tags:
        - Generate
      description: Generate source
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GenerateRequestBody'
      responses:
        200:
          description: The query is successful
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  additionalProperties:
                    type: string
        400:
          $ref: '#/components/responses/BadRequest'
        401:
          $ref: '#/components/responses/AuthenticationError'
        403:
          $ref: '#/components/responses/Unauthorized'
        404:
          $ref: '#/components/responses/NotFound'
        500:
          $ref: '#/components/responses/ServerError'
components:
  schemas:
    Field:
      type: object
      required:
        - id
        - name
        - sqlType
        - generateType
        - option
      description: FIELD table
      properties:
        id:
          readOnly: true
          type: string
          description: id of table
        name:
          type: string
          description: name of field
        sqlType:
          $ref: '#/components/schemas/SQLType'
        generateType:
          $ref: '#/components/schemas/GenerateType'
        option:
          $ref: '#/components/schemas/Option'
    SQLType:
      type: object
      required:
        - id
        - code
        - description
      description: SQLTYPE table
      properties:
        id:
          readOnly: true
          type: string
          description: id of table
        code:
          type: string
          description: name of field
        description:
          type: string
          description: type in SQL
        generateTypes:
          type: array
          items:
            $ref: '#/components/schemas/GenerateType'
    GenerateType:
      type: object
      required:
        - id
        - code
        - description
        - category
      description: GENERATETYPE table
      properties:
        id:
          readOnly: true
          type: string
          description: id of table
        code:
          type: string
          description: code for generate
        description:
          type: string
          description: description for generate type
        category:
          $ref: '#/components/schemas/Category'
        source:
          type: array
          items:
            $ref: '#/components/schemas/Source'
        sqlTypes:
          type: array
          items:
            $ref: '#/components/schemas/SQLType'
    Category:
      type: object
      required:
        - id
        - type
        - description
      description: CATEGORY table
      properties:
        id:
          readOnly: true
          type: string
          description: id of table
        type:
          type: string
          description: name of category
        description:
          type: string
          description: description for generate type
        generateTypes:
          type: array
          items:
            $ref: '#/components/schemas/GenerateType'
    Source:
      type: object
      required:
        - id
        - value
        - generateType
      description: Source table
      properties:
        id:
          readOnly: true
          type: string
          description: id of table
        value:
          type: string
          description: value of source
        generateType:
          $ref: '#/components/schemas/GenerateType'
    Option:
      type: object
      required:
        - id
        - blank
      description: OPTION table
      properties:
        id:
          readOnly: true
          type: string
          description: id of table
        blank:
          default: 0
          type: integer
          description: blank percent
    Error:
      description: Schema for error response body
      type: object
      properties:
        timestamp:
          type: string
        status:
          type: integer
        error:
          type: string
        message:
          type: string
        path:
          type: string
        code:
          enum:
            - UNEXPECTED_EXCEPTION
            - AUTHENTICATION_EXCEPTION
            - PERMISSION_EXCEPTION
            - BAD_REQUEST
            - NOT_FOUND
            - CONFLICT
            - INVALID_STATUS
            - INVALID_PROPERTIES
            - ACTION_NOT_ALLOWED
          description: |
            Ged error code:
            * UNEXPECTED_EXCEPTION - unexpected error.
            * AUTHENTICATION_EXCEPTION - user is not authenticated.
            * PERMISSION_EXCEPTION - user does not have permission to perform the action.
            * BAD_REQUEST - the request is wrong.
            * NOT_FOUND - resource not found.
            * CONFLICT - business error.
            * INVALID_STATUS - resource status is not valid.
            * INVALID_PROPERTIES - the properties is not valid.
            * ACTION_NOT_ALLOWED - the action not allowed.
        additionalMessage:
          type: string
    GenerateRequestBody:
      type: object
      description: The body of generate request
      required:
        - row
        - format
        - tableName
        - fields
      properties:
        row:
          readOnly: true
          type: integer
          default: 0
          description: Row number of source
        format:
          readOnly: true
          type: string
          default: "SQL"
          description: Format of source
        tableName:
          readOnly: true
          type: string
          description: Name of table
        fields:
          readOnly: true
          type: array
          items:
            $ref: '#/components/schemas/Field'
          description: Fields of table
  responses:
    NotFound:
      description: The specified resource was not found
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Error'
    AuthenticationError:
      description: Authentication Error
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Error'
    Unauthorized:
      description: Unauthorized, access to this resource is not allowed
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Error'
    BadRequest:
      description: Bad request, invalid query syntax
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Error'
    ServerError:
      description: Internal Server Error
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Error'