/**
 * @author Do Quoc Viet
 * @class ErrorCode
 * @date 04/03/2023
 */
export enum ErrorCode {
  UNEXPECTED_EXCEPTION = 'UNEXPECTED_EXCEPTION',

  AUTHENTICATION_EXCEPTION = 'AUTHENTICATION_EXCEPTION',

  PERMISSION_EXCEPTION = 'PERMISSION_EXCEPTION',

  BAD_REQUEST = 'BAD_REQUEST',

  NOT_FOUND = 'NOT_FOUND',

  CONFLICT = 'CONFLICT',

  INVALID_STATUS = 'INVALID_STATUS',

  INVALID_PROPERTIES = 'INVALID_PROPERTIES',

  ACTION_NOT_ALLOWED = 'ACTION_NOT_ALLOWED'
}
