spring:
  datasource:
    url: jdbc:postgresql://dpg-ch6u2krhp8u9bo4c50kg-a.oregon-postgres.render.com:5432/mocker
    username: mocker_user
    password: NsNNzUn33yw6xG6nmjkNzFV6vN3Xd033
  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: mocker.service@gmail.com
    password: dsgzfgwatuwujntb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 405114314484-rdp9bj491f6bd6kj3u9fqimstqfn9mmg.apps.googleusercontent.com
            clientSecret: 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
  thymeleaf:
    check-template-location: false