package com.mockez.service.impl;

import com.mockez.domain.model.Data;
import com.mockez.domain.model.Field;
import com.mockez.domain.model.GenerateRequestBody;
import com.mockez.repository.GenTypeRepository;
import com.mockez.service.GenerateService;
import lombok.AllArgsConstructor;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.Random;

import static com.mockez.constant.GenerateConstant.*;

@Service
@AllArgsConstructor
public class GenerateServiceImpl implements GenerateService {

    private GenTypeRepository genTypeRepository;

    @Override
    public String generate(GenerateRequestBody body) {

        StringBuilder result = new StringBuilder("""
                -- NOTE: This file is auto generated by Mockez Generator
                -- Website: https://mockez.com
                -- Version: 0.0.1-SNAPSHOT)
                -- Author: Ho Chi Minh City University of Technology and Education
                """);

        List<Field> fields = body.getFields()
                .stream()
                .map(field -> field.genType(genTypeRepository.fetchGenTypeData(field.getGenType().getId())))
                .toList();

        if (body.getIsIncludeCreateTable()) {
            result.append(TEMPLATE_INSERT_BUILDER);
        }

        String template = String.format(TEMPLATE_INSERT_BUILDER,
                        body.getTableName(),
                        fields.stream().map(field -> BACKTICK + field.getName() + BACKTICK + COMMA_SPACE))
                .replaceFirst(", \\)", ")");

        int index = 0;
        while (++index < body.getRow()) {
            String values = fields.stream()
                    .map(field -> getValueFromAlgorithm(field.getGenType().getData()
                            .stream()
                            .map(Data::getValue)
                            .toList()))
                    .map(value -> BACKTICK + value + BACKTICK + COMMA_SPACE)
                    .toString()
                    .replaceFirst(", \\)", ")");
            result.append(template.replaceAll("/values/", values));
        }
        return result.toString();
    }

    private String getValueFromAlgorithm(List<String> values) {
        return values.get(new Random().nextInt(0, values.size() - 1));
    }
}
