spring:
  datasource:
    url: jdbc:postgresql://dpg-ch6u2krhp8u9bo4c50kg-a.oregon-postgres.render.com:5432/mocker
    username: mocker_user
    password: NsNNzUn33yw6xG6nmjkNzFV6vN3Xd033
  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: mocker.service@gmail.com
    password: 0393014871
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  thymeleaf:
    check-template-location: false